[project]
name = "commsearch-abm272"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "commsearch",
    "icebug",
    "format-conversion",
    "click",
    "polars",
    "pyarrow",
    "numpy",
]

[tool.uv.sources]
commsearch = { git = "https://github.com/IanChenUIUC/community_search", subdirectory = "src/ours-python-commsearch" }
icebug = { git = "https://github.com/IanChenUIUC/icebug", branch = "feature/kcore-commsearch" }
format-conversion = { git = "https://github.com/IanChenUIUC/format-conversion", branch = "feature/cleanup-options" }

[tool.ruff]
line-length = 100

