[defaults.slurm]
cpus = 16
mem  = "128GB"
time = "4:00:00"
partition = "secondary"

[defaults]
# root = "/models/ianchen3/community_search"
root = "/u/ianchen3/community_search"
input = "${root}/input"
output = "${root}/output"

[recipe.build]
stdout  = "${output}/build.out"
stderr  = "${output}/build.err"
timing  = "${output}/build.resources"

command = """
mkdir -p ${input}
mkdir -p ${output}
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- bash -c "
  cd ${root}/src/gbbs-core-decomposition && bazel build //...
  cd ${root}/src/ucrparlay-core-decomposition/KCore && make
  cd ${root}/src/pkc-core-decomposition && make
  cd ${root}/src/csk-commsearch && make
  cd ${root}/src/gullo-shellstruct && mvn compile
  cd ${root}/src/utilities && uv sync
  cd ${root}/src/lbug-core-decomposition && uv sync
  cd ${root}/src/networkit-core-decomposition && uv sync
  cd ${root}/src/ours-icebug-commsearch && uv sync
  cd ${root}/src/ours-python-commsearch && uv sync
  cd ${root}/src/gen-query && uv sync
" 1> ${stdout} 2> ${stderr} 
"""

[recipe.gbbs-format]
array   = true
slurm   = { mem = "256GB" }
params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
deps    = ["build"]

stdout  = "${output}/${dataset}/gbbs-format/stdout.txt"
stderr  = "${output}/${dataset}/gbbs-format/stderr.txt"
timing  = "${output}/${dataset}/gbbs-format/timing.txt"

command = """
mkdir -p ${output}/${dataset}/gbbs-format
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/utilities/csv2gbbs.sh  \
    ${input}/${dataset}.csv \
    ${input}/${dataset}.gbbs.adj \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -a -o ${timing} -- \
  ${root}/src/gbbs-core-decomposition/bazel-bin/utils/converter -s -enc binary \
    -o ${input}/${dataset}.gbbs.bin \
    ${input}/${dataset}.gbbs.adj \
  1> >(tee -a ${stdout}) 2> >(tee -a ${stderr})
"""

[recipe.pkc-format]
array   = true
params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
deps    = ["build"]

stdout  = "${output}/${dataset}/pkc-format/stdout.txt"
stderr  = "${output}/${dataset}/pkc-format/stderr.txt"
timing  = "${output}/${dataset}/pkc-format/timing.txt"

command = """
mkdir -p ${output}/${dataset}/pkc-format
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/utilities/csv2pkc.sh  \
    ${input}/${dataset}.csv \
    ${input}/${dataset}.pkc.adj \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.nk-format]
array   = true
# params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
params  = { dataset = ["abm14", "cen"] }
deps    = ["build"]

stdout  = "${output}/${dataset}/nk-format/stdout.txt"
stderr  = "${output}/${dataset}/nk-format/stderr.txt"
timing  = "${output}/${dataset}/nk-format/timing.txt"

command = """
mkdir -p ${output}/${dataset}/nk-format
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/networkit-core-decomposition/.venv/bin/python ${root}/src/networkit-core-decomposition/csv2nk.py \
    --edgelist ${input}/${dataset}.csv \
    --output ${input}/${dataset}.nk.bin \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.csr-format]
array   = true
params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
deps    = ["build"]

stdout  = "${output}/${dataset}/csr-format/stdout.txt"
stderr  = "${output}/${dataset}/csr-format/stderr.txt"
timing  = "${output}/${dataset}/csr-format/timing.txt"

command = """
mkdir -p ${output}/${dataset}/csr-format
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/utilities/.venv/bin/python ${root}/src/utilities/csv2csr.py  \
    ${input}/${dataset}.csv \
    ${input}/${dataset} \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -a -o ${timing} -- \
  ${root}/src/utilities/.venv/bin/python ${root}/src/utilities/pq2pf.py -w 32 \
    ${input}/${dataset}.indices.parquet \
  1> >(tee -a ${stdout}) 2> >(tee -a ${stderr})
mv ${input}/${dataset}.indices.feather ${input}/${dataset}.indices32.feather
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -a -o ${timing} -- \
  ${root}/src/utilities/.venv/bin/python ${root}/src/utilities/pq2pf.py \
    ${input}/${dataset}.indptr.parquet \
    ${input}/${dataset}.indices.parquet \
  1> >(tee -a ${stdout}) 2> >(tee -a ${stderr}) 
"""

### Removing Ladybug from the experiment
# [recipe.lbug-format]
# array   = true
# params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
# deps    = ["build"]

# stdout  = "${output}/${dataset}/lbug-format/stdout.txt"
# stderr  = "${output}/${dataset}/lbug-format/stderr.txt"
# timing  = "${output}/${dataset}/lbug-format/timing.txt"

# command = """
# mkdir -p ${output}/${dataset}/lbug-format
# uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -a -o ${timing} -- \
#   uv run --project ${root}/src/utilities ${root}/src/utilities/csv2csr.py  \
#     ${input}/${dataset}.csv \
#     ${input}/${dataset}.lbug \
#     --no-symmetrize \
#   1> >(tee ${stdout}) 2> >(tee ${stderr})
# """

[recipe.gbbs-core-decomp]
array   = true
# params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
params  = { dataset = ["abm14", "cen"] }
deps    = ["gbbs-format(dataset=${dataset})"]
slurm   = { cpus = 16, exclusive = true }

stdout  = "${output}/${dataset}/gbbs-core-decomp/stdout.txt"
stderr  = "${output}/${dataset}/gbbs-core-decomp/stderr.txt"
timing  = "${output}/${dataset}/gbbs-core-decomp/timing.txt"

command = """
mkdir -p ${output}/${dataset}/gbbs-core-decomp
export PARLAY_NUM_THREADS=${slurm.cpus}
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/gbbs-core-decomposition/bazel-bin/benchmarks/KCore/JulienneDBS17/KCore_main -s -b -rounds 1 \
    -o ${output}/${dataset}/gbbs-core-decomp/cores.csv \
    ${input}/${dataset}.gbbs.bin \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.ucr-core-decomp]
array   = true
# params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
params  = { dataset = ["abm14", "cen"] }
deps    = ["gbbs-format(dataset=${dataset})"]
slurm   = { cpus = 16, exclusive = true }

stdout  = "${output}/${dataset}/ucr-core-decomp/stdout.txt"
stderr  = "${output}/${dataset}/ucr-core-decomp/stderr.txt"
timing  = "${output}/${dataset}/ucr-core-decomp/timing.txt"

command = """
mkdir -p ${output}/${dataset}/ucr-core-decomp
export PARLAY_NUM_THREADS=${slurm.cpus}
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/ucrparlay-core-decomposition/KCore/kcore -s \
    -i ${input}/${dataset}.gbbs.bin \
    -o ${output}/${dataset}/ucr-core-decomp/cores.csv \
    -l ${stdout} \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.pkc-core-decomp]
array   = true
# params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
params  = { dataset = ["abm14", "cen"] }
deps    = ["pkc-format(dataset=${dataset})"]
slurm   = { cpus = 16, exclusive = true }

stdout  = "${output}/${dataset}/pkc-core-decomp/stdout.txt"
stderr  = "${output}/${dataset}/pkc-core-decomp/stderr.txt"
timing  = "${output}/${dataset}/pkc-core-decomp/timing.txt"

command = """
mkdir -p ${output}/${dataset}/pkc-core-decomp
export OMP_NUM_THREADS=${slurm.cpus}
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/pkc-core-decomposition/pkc.exe \
    ${input}/${dataset}.pkc.adj \
    ${output}/${dataset}/pkc-core-decomp/cores.csv \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

### removing Ladybug from the experiment
# [recipe.lbug-core-decomp]
# array   = true
# params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
# deps    = ["lbug-format(dataset=${dataset})"]

# stdout  = "${output}/${dataset}/lbug-core-decomp/stdout.txt"
# stderr  = "${output}/${dataset}/lbug-core-decomp/stderr.txt"
# timing  = "${output}/${dataset}/lbug-core-decomp/timing.txt"

# command = """
# mkdir -p ${output}/${dataset}/lbug-core-decomp
# uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -a -o ${timing} -- \
#   uv run --project ${root}/src/lbug-core-decomposition ${root}/src/lbug-core-decomposition/main.py \
#     ${input}/${dataset}.lbug.indptr.parquet \
#     ${input}/${dataset}.lbug.indices.parquet \
#     ${output}/${dataset}/lbug-core-decomp/cores.csv \
#   1> >(tee ${stdout}) 2> >(tee ${stderr})
# """

[recipe.nk-core-decomp]
array   = true
# params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
params  = { dataset = ["abm14", "cen"] }
deps    = ["nk-format(dataset=${dataset})"]
slurm   = { cpus = 16, exclusive = true }

stdout  = "${output}/${dataset}/nk-core-decomp/stdout.txt"
stderr  = "${output}/${dataset}/nk-core-decomp/stderr.txt"
timing  = "${output}/${dataset}/nk-core-decomp/timing.txt"

command = """
mkdir -p ${output}/${dataset}/nk-core-decomp
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/networkit-core-decomposition/.venv/bin/python ${root}/src/networkit-core-decomposition/main.py \
    --graph ${input}/${dataset}.nk.bin \
    --output ${output}/${dataset}/nk-core-decomp/cores.csv \
    --threads ${slurm.cpus} \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.ib-core-decomp]
array   = true
# params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
params  = { dataset = ["abm14", "cen"] }
deps    = ["csr-format(dataset=${dataset})"]
slurm   = { cpus = 16, exclusive = true }

stdout  = "${output}/${dataset}/ib-core-decomp/stdout.txt"
stderr  = "${output}/${dataset}/ib-core-decomp/stderr.txt"
timing  = "${output}/${dataset}/ib-core-decomp/timing.txt"

command = """
mkdir -p ${output}/${dataset}/ib-core-decomp
export LD_LIBRARY_PATH=$(
    ${root}/src/ours-icebug-commsearch/.venv/bin/python -c "import pyarrow; print(pyarrow.get_library_dirs()[0])"
  ):$LD_LIBRARY_PATH
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/ours-icebug-commsearch/.venv/bin/python ${root}/src/ours-icebug-commsearch/core_decomposition.py \
    ${input}/${dataset}.indptr.feather \
    ${input}/${dataset}.indices.feather \
    ${output}/${dataset}/ib-core-decomp/cores.csv \
    --threads ${slurm.cpus} \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.network-stats]
# params  = [
#   { dataset = "abm14" }, { dataset = "bitcoin" }, { dataset = "cen" }, { dataset = "dbpedia_link" }, { dataset = "livejournal" }, { dataset = "microsoft_concept" }, { dataset = "wikipedia_link" },
#   { dataset = "friendster", slurm = { mem = "256GB" } },
#   { dataset = "twitter_social", slurm = { mem = "256GB" } },
# ]
array   = true
params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
deps    = ["csr-format(dataset=${dataset})"]

stdout  = "${output}/${dataset}/network-stats/stdout.txt"
stderr  = "${output}/${dataset}/network-stats/stderr.txt"
timing  = "${output}/${dataset}/network-stats/timing.txt"

command = """
mkdir -p ${output}/${dataset}/network-stats
export LD_LIBRARY_PATH=$(
    ${root}/src/ours-icebug-commsearch/.venv/bin/python -c "import pyarrow; print(pyarrow.get_library_dirs()[0])"
  ):$LD_LIBRARY_PATH
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/ours-icebug-commsearch/.venv/bin/python ${root}/src/ours-icebug-commsearch/network-stats.py \
    ${input}/${dataset}.indptr.feather \
    ${input}/${dataset}.indices.feather \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.shellstruct-strong-scaling]
params  = { dataset = ["abm14", "cen"] }
deps    = ["csr-format(dataset=${dataset})"]
slurm   = { cpus = 64, exclusive = true }

stdout  = "${output}/${dataset}/shellstruct-strong-scaling/stdout.txt"
stderr  = "${output}/${dataset}/shellstruct-strong-scaling/stderr.txt"
timing  = "${output}/${dataset}/shellstruct-strong-scaling/timing.txt"

command = """
mkdir -p ${output}/${dataset}/shellstruct-strong-scaling
export LD_LIBRARY_PATH=$(
    ${root}/src/ours-icebug-commsearch/.venv/bin/python -c "import pyarrow; print(pyarrow.get_library_dirs()[0])"
  ):$LD_LIBRARY_PATH
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/ours-icebug-commsearch/.venv/bin/python ${root}/src/ours-icebug-commsearch/shellstruct_strong_scaling.py \
    ${input}/${dataset}.indptr.feather \
    ${input}/${dataset}.indices.feather \
    ${output}/${dataset}/shellstruct-strong-scaling/curve.csv
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.centrality]
params  = { dataset = ["cen", "abm14"] }
deps    = ["nk-format(dataset=${dataset})"]

stdout  = "${output}/${dataset}/centrality/stdout.txt"
stderr  = "${output}/${dataset}/centrality/stderr.txt"
timing  = "${output}/${dataset}/centrality/timing.txt"

command = """
mkdir -p ${output}/${dataset}/centrality
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/networkit-core-decomposition/.venv/bin/python ${root}/src/networkit-core-decomposition/centrality.py \
    --graph ${input}/${dataset}.nk.bin \
    --output ${output}/${dataset}/centrality/centrality.csv \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.icebug-shell-struct]
array   = true
params  = { dataset = ["abm14", "bitcoin", "cen", "dbpedia_link", "friendster", "livejournal", "microsoft_concept", "twitter_social", "wikipedia_link"] }
deps    = ["csr-format(dataset=${dataset})"]

stdout  = "${output}/${dataset}/icebug-shell-struct/stdout.txt"
stderr  = "${output}/${dataset}/icebug-shell-struct/stderr.txt"
timing  = "${output}/${dataset}/icebug-shell-struct/timing.txt"

command = """
mkdir -p ${output}/${dataset}/icebug-shell-struct
export LD_LIBRARY_PATH=$(
    ${root}/src/ours-icebug-commsearch/.venv/bin/python -c "import pyarrow; print(pyarrow.get_library_dirs()[0])"
  ):$LD_LIBRARY_PATH
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing} -- \
  ${root}/src/ours-icebug-commsearch/.venv/bin/python ${root}/src/ours-icebug-commsearch/build_shellstruct.py \
    ${input}/${dataset}.indptr.feather \
    ${input}/${dataset}.indices.feather \
    ${output}/${dataset}/icebug-shell-struct/shell \
  1> >(tee ${stdout}) 2> >(tee ${stderr})
"""

[recipe.cold-warm]
params  = { dataset = ["cen", "abm14"] }
deps    = ["csr-format(dataset=${dataset})"]

stdout  = "${output}/${dataset}/cold-warm/stdout.txt"
stderr  = "${output}/${dataset}/cold-warm/stderr.txt"
timing  = "${output}/${dataset}/cold-warm/timing"

command = """
export root=${root}
export input=${input}
export output=${output}
export dataset=${dataset}
export stdout=${stdout}
export stderr=${stderr}
export timing=${timing}
bash ${root}/src/cold-warm/run.sh
"""

[recipe.ours-py-v-ib]
params  = { dataset = ["cen", "abm14"] }
deps    = ["csr-format(dataset=${dataset})", "ib-core-decomp(dataset=${dataset})"]

stdout  = "${output}/${dataset}/ours-py-v-ib/stdout.txt"
stderr  = "${output}/${dataset}/ours-py-v-ib/stderr.txt"
timing  = "${output}/${dataset}/ours-py-v-ib/timing"

command = """
mkdir -p ${output}/${dataset}/ours-py-v-ib
export LD_LIBRARY_PATH=$(
    ${root}/src/ours-icebug-commsearch/.venv/bin/python -c "import pyarrow; print(pyarrow.get_library_dirs()[0])"
  ):$LD_LIBRARY_PATH

## generate queries
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing}-genquery.txt -- \
  ${root}/src/gen-query/.venv/bin/python ${root}/src/gen-query/py_v_ib.py \
    ${input}/${dataset}.indptr.feather \
    ${input}/${dataset}.indices.feather \
    ${output}/${dataset}/ours-py-v-ib/query.csv \
  1> >(tee ${stdout}) 2> >(tee ${stderr})

## icebug shell-struct building
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing}-icebug_build_shell.txt -- \
  ${root}/src/ours-icebug-commsearch/.venv/bin/python ${root}/src/ours-icebug-commsearch/build_shellstruct.py \
    ${input}/${dataset}.indptr.feather \
    ${input}/${dataset}.indices.feather \
    ${output}/${dataset}/ours-py-v-ib/icebug_shell \
    ${output}/${dataset}/ib-core-decomp/cores.csv \
  1> >(tee -a ${stdout}) 2> >(tee -a ${stderr})

## icebug shell-struct search
uv run --project ${root}/src/utilities ${root}/src/utilities/mytime.py -o ${timing}-icebug_query_shell.txt -- \
  ${root}/src/ours-icebug-commsearch/.venv/bin/python ${root}/src/ours-icebug-commsearch/query_shellstruct.py \
    ${input}/${dataset}.indptr.feather \
    ${input}/${dataset}.indices.feather \
    ${output}/${dataset}/ours-py-v-ib/icebug_shell.components.feather \
    ${output}/${dataset}/ours-py-v-ib/icebug_shell.tree.feather \
    ${output}/${dataset}/ours-py-v-ib/query.csv \
    ${output}/${dataset}/ours-py-v-ib/icebug_shell_querytimes.csv \
  1> >(tee -a ${stdout}) 2> >(tee -a ${stderr})
"""
